theme: minima

title: Kar-Han Tan's Home Page - karhan-tan.github.io
email: karhan@helpful-robotics.com
description: > # this means to ignore newlines until "baseurl:"
  Kar-Han Tan's home page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  karhan-tan

gems:
  - jekyll-feed
